spool /u01/app/oracle/scripts/refresh/logs/DSGN_user_create.log

CREATE USER ANG
  IDENTIFIED BY "abcdef1234"
  DEFAULT TABLESPACE GTAPP_SPACE
  TEMPORARY TABLESPACE TEMPORARY
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for ANG 
  GRANT CONNECT TO ANG;
  GRANT GTBROWSE_ROLE TO ANG;
  GRANT SELECT_CATALOG_ROLE TO ANG;
  ALTER USER ANG DEFAULT ROLE ALL;

spool off
exit;
